name: CI
env:
  tag: python:latest
on:
  push:
    branches: main
jobs:
  Create_Env_Var:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: Run Windows Command
       run: |
         python test.py
         
  call-workflow-passing-data:
   uses: shikha227/runner-demo/.github/workflows/resuable.yaml@main
   with:
     tag: python:latest
