name: CI
env:
  tag: python:latest
on:
  push:
    branches: main
jobs:
  Run_PY_Script:
    runs-on: ubuntu-latest
    container: ${{ env.tag }}
    steps:
     - uses: actions/checkout@v3
     - name: Run Windows Command
       run: |
         python test.py
